import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <nav className="flex justify-center space-x-8 !bg-transparent font-semibold text-white underline py-2">
        <Link href="/">Home</Link>
        <Link href="/about">About</Link>
        <Link href="/city">Cities</Link>
      </nav>
      <main>{children}</main>
    </>
  );
}
